main:
- name: Blog
  url: /posts/
  weight: 1

- name: Teaching
  url: /teaching/
  weight: 2

- name: Biography
  url: /bio/
  weight: 3

- name: Curriculum Vitae
  url: /cv/
  weight: 4

- name: Projects
  url: /projects/
  weight: 5

social:
- name: email
  url: mailto:sanjeets1900@gmail.com
  weight: 1
  params:
    icon: fas fa-envelope

- name: LinkedIn
  url: https://www.linkedin.com/in/sanjeetshukla/
  weight: 2
  params:
    icon: fab fa-linkedin

- name: GitHub
  url: https://github.com/sanjeet-shukla
  weight: 3
  params:
    icon: fab fa-github

- name: RSS Feed
  url: /index.xml
  weight: 4
  params:
    icon: fas fa-square-rss
